supabase_url: >-
  U2FsdGVkX1+aAppCryXDrJcgI6JcJEqaAAhwGo+ZhC2tfhzF0Q+VL7Dlo4DsxyF5UIIZpNM9T/qL2ka98hOwLQ==
supabase_key: >-
  U2FsdGVkX18QNA2J2Sg5n25nA4gk9BKHAxuYukDFBMVKZ5UUGDYB+i3UFmzwVgGhDbVdF3iboI+YsfJYyuoEiCscSBpfFmn7aHRwNgvgDn5Nm1kH7bng4i1N/HAKaVXzTWn3nCd7UecTQ4TfYns1mLWsMe3mU70ENQaZSmfm71/lGoH+JhneoXLtxPWrO0uIEVo5i9QqT4FvicIpxk9aCttKMJB9fUkQqQUNzGP9/j3SJIhNxYLjH1xE0E/Z27kU2DidLu9z411l6RGgMSwiNJsEBFKWHCW3+KHjXalgqhWH9Vuon/o668fiUqRYXKwH
claude_key: U2FsdGVkX1853bdj/v31i1AzB9TJRmo2Jj8n6hcpZFI=
openrouter_key: >-
  U2FsdGVkX19tooL2gQurV27wfZ4kfTKoX2B8pVPSC12Ts44iGjF0V9XkIR3/rAGnSgDhvIr8smFhK7SSkSPdw3Q4xXvc4ipm6HbLQcEN4WIZn+xyERmeltSBMsLZCXYD
app_password: U2FsdGVkX19csd5cg2dnESuWvzxPLHEm/519DhBmzHI=
height_cm: U2FsdGVkX1/25qtybXnuRugM1ddT5z1xIW12h2r6CuE=
